# for data manipulation
import pandas as pd
# for creating a folder
import os
# for data preprocessing and pipeline creation
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
# for hugging face space authentication to upload files
from huggingface_hub import login, HfApi

# Define constants for the dataset and output paths
api = HfApi(token=os.getenv("HF_TOKEN"))
DATASET_PATH = "hf://datasets/vijayendras/superkart-sales-data/superkart.csv"
superkart_df = pd.read_csv(DATASET_PATH)
print("Dataset loaded successfully.")

# ----------------------------
# Clean Data for processing
# ----------------------------

superkart_df = superkart_df.drop(columns=["Product_Id", "Store_Id"])

superkart_df["Store_Age"] = 2026 - superkart_df["Store_Establishment_Year"]

superkart_df = superkart_df.drop(columns=["Store_Establishment_Year"])

# ----------------------------
# Define the target variable
# ----------------------------
target = 'Product_Store_Sales_Total'   # Total revenue generated by the sale of that particular product in that particular store

# ----------------------------
# List of numerical features
# ----------------------------
numeric_features = [
    'Product_Weight',         # What is the weight of the product
    'Product_Allocated_Area',            # What is the ratio of the allocated display area of the product to the total display area of all the products in the store
    'Product_MRP',  # MRP of the product
    'Store_Age' # How old is the store
]

# ----------------------------
# List of categorical features
# ----------------------------
categorical_features = [
    'Product_Sugar_Content',             # what is the sugar content of the product like low sugar, regular and no sugar
    'Product_Type',   # Broad category of the product like meat, snacks, dairy etc
    'Store_Size',       # Category of the size as per store size as high, medium, low
    'Store_Location_City_Type',          # Type of city like Tier1, Tier2
    'Store_Type'       # Type of store like Supermarket, departmental store
]


# ----------------------------
# Combine features to form X (feature matrix)
# ----------------------------
X = superkart_df[numeric_features + categorical_features]

# ----------------------------
# Define target vector y
# ----------------------------
y = superkart_df[target]

# ----------------------------
# Split dataset into training and test sets
# ----------------------------
Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=42
)

Xtrain.to_csv("Xtrain.csv",index=False)
Xtest.to_csv("Xtest.csv",index=False)
ytrain.to_csv("ytrain.csv",index=False)
ytest.to_csv("ytest.csv",index=False)


files = ["Xtrain.csv","Xtest.csv","ytrain.csv","ytest.csv"]

for file_path in files:
    api.upload_file(
        path_or_fileobj=file_path,
        path_in_repo=file_path.split("/")[-1],  # just the filename
        repo_id="vijayendras/superkart-sales-data",
        repo_type="dataset",
    )
